stag:
    resource: "@StagBundle/Controller/"
    type:     annotation
    prefix:   /

guser:
    resource: '@GuserBundle/Controller/'
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
