<?php

namespace StagBundle\Repository;

/**
 * BlobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlobRepository extends \Doctrine\ORM\EntityRepository {
}
